include: package:lint_hard/all.yaml
analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_classes_with_only_static_members: ignore
    document_ignores: ignore
    library_private_types_in_public_api: ignore
    lines_longer_than_80_chars: ignore
    sort_constructors_first: ignore
    type_annotate_public_apis: ignore
    unnecessary_async: ignore

linter:
  rules:
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    diagnostic_describe_all_properties: false

